server:
  context-path: /micro
  port: 8080

spring:
  cloudant:
    username: ${vcap.services.lightblue-cloiudant.credentials.username}
    password: ${vcap.services.lightblue-cloiudant.credentials.password}
    host: ${vcap.services.lightblue-cloiudant.credentials.host}
    protocol: https
    port: 443
    database: customers
 